name: userapp
description: 'Junkfood User App'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_carousel_widget: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2
  supabase_flutter: ^2.4.0
  riverpod_annotation: ^2.3.5
  supabase_auth_ui: ^0.4.3
  hooks_riverpod: ^2.5.1
  build_runner: ^2.4.9
  gradient_elevated_button: ^0.0.8

dev_dependencies:
  flutter_launcher_icons: '^0.13.1'
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'lib/resources/logo.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'lib/resources/logo.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'lib/resources/logo.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'lib/resources/logo.png'

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-VariableFont_wght.ttf
