name: userapp
description: "Junkfood User App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_carousel_widget: ^2.2.0
  flutter_guid: ^0.3.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  gradient_elevated_button: ^0.0.8
  hooks_riverpod: ^2.5.1
  intl: any
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  supabase_auth_ui: ^0.4.3
  supabase_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: ^0.6.4
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/resources/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/resources/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/resources/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/resources/logo.png"

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-VariableFont_wght.ttf
