create table "public"."Ratings" (
    "id" bigint generated by default as identity not null,
    "rating" bigint not null,
    "dish_id" bigint
);


alter table "public"."Ratings" enable row level security;

CREATE UNIQUE INDEX "Rating_pkey" ON public."Ratings" USING btree (id);

alter table "public"."Ratings" add constraint "Rating_pkey" PRIMARY KEY using index "Rating_pkey";

alter table "public"."Ratings" add constraint "public_Ratings_dish_id_fkey" FOREIGN KEY (dish_id) REFERENCES "Dishes"(id) not valid;

alter table "public"."Ratings" validate constraint "public_Ratings_dish_id_fkey";

grant delete on table "public"."Ratings" to "anon";

grant insert on table "public"."Ratings" to "anon";

grant references on table "public"."Ratings" to "anon";

grant select on table "public"."Ratings" to "anon";

grant trigger on table "public"."Ratings" to "anon";

grant truncate on table "public"."Ratings" to "anon";

grant update on table "public"."Ratings" to "anon";

grant delete on table "public"."Ratings" to "authenticated";

grant insert on table "public"."Ratings" to "authenticated";

grant references on table "public"."Ratings" to "authenticated";

grant select on table "public"."Ratings" to "authenticated";

grant trigger on table "public"."Ratings" to "authenticated";

grant truncate on table "public"."Ratings" to "authenticated";

grant update on table "public"."Ratings" to "authenticated";

grant delete on table "public"."Ratings" to "service_role";

grant insert on table "public"."Ratings" to "service_role";

grant references on table "public"."Ratings" to "service_role";

grant select on table "public"."Ratings" to "service_role";

grant trigger on table "public"."Ratings" to "service_role";

grant truncate on table "public"."Ratings" to "service_role";

grant update on table "public"."Ratings" to "service_role";

-- Ratings
create policy "Enable insert for authenticated anon only" on "public"."Ratings" as permissive for insert to anon with check (true);


