-- Create the Strings table
CREATE TABLE Strings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL,
  value text NOT NULL,
  language text NOT NULL,
  created_at timestamp WITH TIME ZONE DEFAULT NOW(),
  updated_at timestamp WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT unique_key_language UNIQUE (key, language)
);

-- Create index for faster queries
CREATE INDEX idx_strings_key_language ON Strings (key, language);

-- Function to update the updated_at field
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at on row update
CREATE TRIGGER trigger_update_updated_at
BEFORE UPDATE ON Strings
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Enable RLS (optional but recommended)
ALTER TABLE Strings ENABLE ROW LEVEL SECURITY;

-- Public read access policy
CREATE POLICY "Allow public read access to Strings"
ON Strings FOR SELECT
USING (true);

-- Insert English Strings
INSERT INTO Strings (key, value, language) VALUES
  ('homePageTitle', 'Homepage', 'en'),
  ('allergens', 'Allergens', 'en'),
  ('noAllergens', 'No allergens', 'en'),
  ('noDishText', 'Today''s menu will be available at 13:00', 'en'),
  ('calories', 'Calories', 'en'),
  ('mainCourse', 'Main Course', 'en'),
  ('dessert', 'Dessert', 'en'),
  ('dishOfTheDay', 'Dish of the day', 'en'),
  ('noDescription', 'No description', 'en'),
  ('noCalories', 'No calories', 'en'),
  ('noTitle', 'No title', 'en'),
  ('noDishType', 'No dishtype', 'en'),
  ('servingHasEndedText', 'Yesterday''s serving has ended.\nToday''s menu will be available at 13:00.', 'en'),
  ('rateButtonText', 'Rate today''s dish', 'en'),
  ('localeHelper', 'en', 'en'),
  ('ratingTitle', 'How was your meal today?', 'en'),
  ('ratingFeedback', 'Help us choose the favorites of the future!', 'en'),
  ('ratingAcknowledgeTitle', 'Thank you for rating!', 'en'),
  ('ratingAcknowledgeText', 'You are always welcome to send us a message.\nYour opinion means a lot to us.', 'en'),
  ('ratingAcknowledgeButton', 'Return to homepage', 'en'),
  ('ratingContinue', 'Continue', 'en'),
  ('commentHeading', 'We''d love to hear from you!', 'en'),
  ('commentPageParagraph', 'Do you have an idea for today''s dish? A special request - or maybe a birthday coming up? Whether it’s feedback, suggestions, or just something on your mind, your opinion matters to us. Send us a message here - we can’t wait to hear from you!', 'en'),
  ('yourNameHintText', 'Your name', 'en'),
  ('writeCommentText', 'Write your feedback here', 'en'),
  ('commentPageSubmitButton', 'Send feedback', 'en'),
  ('changeRating', 'You have rated this dish, would you like to change your rating?', 'en'),
  ('yes', 'Yes', 'en'),
  ('no', 'No', 'en'),
  ('emptyCommentErrorMessage', 'Comment Field must be filled out', 'en'),
  ('succesfulCommentSubmission', 'Comment posted successfully!', 'en'),
  ('failedCommentSubmission', 'Failed to post comment', 'en'),
  ('commentAcknowledgementTitle', 'Thank you for your comment!', 'en'),
  ('commentAcknowledgementText', 'Your opinion means a lot to us', 'en'),
  ('commentAcknowledgementButton', 'Return to homepage', 'en'),
  ('sendUsMsgBtn', 'Send us a message', 'en'),
  ('dishContents', 'The dish contains:', 'en'),
  ('languageEnglish', 'English', 'en'),
  ('languageDanish', 'Dansk', 'en'),
  ('appTitle', 'Junkfood', 'en');

-- Insert Danish Strings
INSERT INTO Strings (key, value, language) VALUES
  ('homePageTitle', 'Startside', 'da'),
  ('allergens', 'Allergener', 'da'),
  ('noAllergens', 'Ingen allergener', 'da'),
  ('noDishText', 'Dagens ret vises kl. 13:00', 'da'),
  ('calories', 'Kalorier', 'da'),
  ('mainCourse', 'Hovedret', 'da'),
  ('dessert', 'Dessert', 'da'),
  ('dishOfTheDay', 'Dagens ret', 'da'),
  ('noDescription', 'Ingen beskrivelse', 'da'),
  ('noCalories', 'Ingen kalorier', 'da'),
  ('noTitle', 'Ingen titel', 'da'),
  ('noDishType', 'Ingen type ret', 'da'),
  ('servingHasEndedText', 'Servering af gårsdagens ret er slut.\nDagens ret vises kl. 13:00.', 'da'),
  ('rateButtonText', 'Bedøm dagens ret', 'da'),
  ('localeHelper', 'da', 'da'),
  ('ratingTitle', 'Hvordan var dagens ret?', 'da'),
  ('ratingFeedback', 'Hjælp os med at vælge fremtidens favoritter!', 'da'),
  ('ratingAcknowledgeTitle', 'Tak for din bedømmelse!', 'da'),
  ('ratingAcknowledgeText', 'Du er altid velkommen til at sende os en besked.\nDin mening betyder meget for os', 'da'),
  ('ratingAcknowledgeButton', 'Tilbage til forsiden', 'da'),
  ('ratingContinue', 'Fortsæt', 'da'),
  ('commentHeading', 'Send os en besked her', 'da'),
  ('commentPageParagraph', 'Har du en idé til dagens ret? Et særligt ønske - eller måske en fødselsdag på vej? Uanset om du har ris, ros eller bare noget på hjerte, betyder din mening meget for os. Vi glæder os til at høre fra dig!', 'da'),
  ('yourNameHintText', 'Dit navn', 'da'),
  ('writeCommentText', 'Skriv din besked her', 'da'),
  ('commentPageSubmitButton', 'Send besked', 'da'),
  ('changeRating', 'Du har bedømt dagens ret. Vil du ændre din bedømmelse?', 'da'),
  ('yes', 'Ja', 'da'),
  ('no', 'Nej', 'da'),
  ('emptyCommentErrorMessage', 'Kommentarfeltet skal være udfyldt', 'da'),
  ('succesfulCommentSubmission', 'Kommentar indsendt!', 'da'),
  ('failedCommentSubmission', 'Kommentar kunne ikke indsendes', 'da'),
  ('commentAcknowledgementTitle', 'Tak for din kommentar!', 'da'),
  ('commentAcknowledgementText', 'Din mening betyder meget for os', 'da'),
  ('commentAcknowledgementButton', 'Tilbage til forsiden', 'da'),
  ('sendUsMsgBtn', 'Send os en besked', 'da'),
  ('dishContents', 'Retten består af:', 'da'),
  ('languageEnglish', 'English', 'da'),
  ('languageDanish', 'Dansk', 'da'),
  ('appTitle', 'Junkfood', 'da');
